# CreateGenomeSizeFile command. The TMPDIR command is required due to a known issue with dotnet
# see https://github.com/dotnet/runtime/issues/3168. The command `unset LD_PRELOAD` avoids the error
# mesage `ERROR: ld.so: object '/pstore/apps/bin/lib/libogrt.so' from LD_PRELOAD cannot be preloaded`
# (cannot open shared object file): ignored
create_genome_size_cmd: 'unset LD_PRELOAD; export TMPDIR=/tmp; ml purge; ml load Singularity/3.5.0; singularity exec -B /pstore/data/:/pstore/data/:rw /pstore/apps/bioinfo/HBVouroboros/pisces_singularity/pisces_s3.5.simg dotnet /app/CreateGenomeSizeFile_5.2.9.122/CreateGenomeSizeFile.dll'
# Pisces command
pisces_cmd: 'unset LD_PRELOAD; export TMPDIR=/tmp; ml purge; ml load Singularity/3.5.0; singularity exec -B /pstore/data/:/pstore/data/:rw /pstore/apps/bioinfo/HBVouroboros/pisces_singularity/pisces_s3.5.simg dotnet /app/Pisces_5.2.9.122/Pisces.dll'
# pisces options (to be more stringent, use `--minvq 20 --minmq=30 --vqfilter 20`).
pisces_opts: '--outputsbfiles true --ssfilter true --rmxnfilter 5,5 --mindp 10 --minvq 0 --minbq 20 --minmq 0 --minvf 0.01 --vqfilter 0 --gvcf true'
# sample annotation file
sample_annotation: '../../testdata/sampleAnnotation'
# reference HBV genome in FASTA format
ref_genome_fa: '../../testdata/reference-genome.fa'
# genus
ref_genome_genus: 'Orthohepadnavirus'
# species
ref_genome_species: 'Hepatitis B Virus'
# build
ref_genome_build: 'payw1.3F (V01460)'
