# project name: output files are named with it
project_name: 'realdata'
# sample annotation file
sample_annotation: '/mnt/projects/HBVouroboros/realdata/sampleAnnotation.txt'

# bowtie2 index of duplicated HBV reference genomes
bowtie2_index: '../HBV_refgenomes/HBV_refgenomes_dup_BOWTIE2/HBV_refgenomes_dup_BOWTIE2'
# blast database
blast_db: '../HBV_refgenomes/HBV_allgenomes.fasta'
