# project name: output files are named with it
project_name: 'rsv'
# sample annotation file
sample_annotation: '/mnt/projects/HBVouroboros/testdata/sampleAnnotation'

# bowtie2 index of duplicated HBV reference genomes
bowtie2_index: 'HBV_refgenomes/HBV_refgenomes_dup_BOWTIE2/HBV_refgenomes_dup_BOWTIE2'

# minimal read length to be considered
min_read_length: 30
