# sample annotation file
sample_annotation: '../../testdata/sampleAnnotation'
# trimmomatic steps
trimmomatic_steps: 'ILLUMINACLIP:/pstore/apps/bioinfo/HBVouroboros/HBVouroboros/trim_reads/config/primers.fasta:2:30:10:2:keepBothReads LEADING:20 TRAILING:20 SLIDINGWINDOW:4:15 MINLEN:35 CROP:140'
